name: 'Recruit Completion Submission Form'
description: "Submit this issue to acknowledge completion of the Copilot Studio Agent Academy Recruit path"
title: "<Insert Name> Recruit Completion Submission"
labels:
  - recruit-completed
body:
  - type: markdown
    attributes:
      value: |
        ### IMPORTANT: We are now issuing badges from the [Global AI community](https://globalai.community). Please ensure you have [signed up for an account](https://globalai.community/auth/login) to view your badge. After you submit your issue, please submit this [form](https://aka.ms/agent-academy-recruit/form) to initiate your badge request.

  - type: checkboxes
    attributes:
      label: Curriculum Completion Validation
      description: Please check this to confirm that you have completed the Agent Academy - Recruit curriculum.
      options:
        - label: I verify that I have completed the Agent Academy - Recruit curriculum.
          required: true

  - type: checkboxes
    attributes:
      label: Solution Verification
      description: Please upload the following two screenshots of your final solution into the field below to confirm that you’ve completed the solution. The screenshots required are listed below.
      options:
        - label: I verify that I have uploaded a screenshot of the Agent configuration with my environment name shown into the field below.
          required: true
        - label: I verify that I have uploaded a screenshot of the final solution file with my environment name shown into the field below.
          required: true

  - type: textarea
    id: Final_solution
    attributes:
      label: Final Solution Screenshots
      description: Please upload both screenshots of your final solution here. The two screenshots required are of your agent configuration with your environment name shown and of the final solution file with your environment name shown.
    validations:
      required: true

  - type: textarea
    id: learnings
    attributes:
      label: Key Learnings and Takeaways
      description: Describe what you learned. Please mention key takeaways from the Recruit path.
    validations:
      required: true

  - type: textarea
    id: challenges
    attributes:
      label: Challenges Faced
      description: Did you encounter any difficulties in the Recruit path? If you have mission-specific feedback, please be sure to include the mission title you are referring to.
    validations:
      required: true

  - type: textarea
    id: final_thoughts
    attributes:
      label: Final Thoughts
      description: Any feedback on how to improve the Recruit path? If you have mission-specific feedback, please be sure to include the mission title you are referring to.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Badge validation form
      description: In order to receive your badge, please fill out the following form - [Badge validation form](https://aka.ms/agent-academy-recruit/form). If you do not submit this form, you will not be eligible to recieve a badge. Please check this box to confirm you have submitted the badge validation form.
      options:
        - label: I verify that I have completed the badge validation form.
          required: true
